### ISSUE TITLE
Conversion of REAL values work not exactly

### ISSUE THREAD

**Issue by Lord-Anubis** [Hopperpop/node-red-contrib-nvl#4]
Hello,

if I transfer a real value, the conversion works not exactly. For example -9,2 in the PLC becomes -9.199999809265137 in NodeRed. I have also tested this with positive values. 3.1 becomes 3.0999999046325684. Is this normal? 

Best regards 

Michael

**Comment by Hopperpop** [comment]
Yes, this is normal when using reals/lreals a.k.a floating point numbers. In the plc it will also be -9.199999809265137 but your engineering tool will round it when displaying. 
Possibly node-red doesn't round it automatic when displaying because it converts the 32-bit real to a 64-bit double. As the error is higher than the smallest error of a 64-bit double, node red won't round it automatically when displaying. (The last part about displaying is just a guess.)

Here is an simple tool that can help you understanding it: [FloatConverter](https://www.h-schmidt.net/FloatConverter/IEEE754.html).

**Comment by Lord-Anubis** [comment]
Thank you very much for the very quick reply. I had node-red-contrib-netvar in use so far. With this version I had not observed this so far. That is why I was wondering.

**Comment by Hopperpop** [comment]
node-red-contrib-netvar never worked for negative numbers as far as I know. This is one of the reasons that I created my own version. I quickly checked the code and it looks like they always round the number to two decimal numbers. If you put 3.125 in my node, it will exactly give 3.125 because there isn't an error representing that in floating point numbers. But node-red-contrib-netvar returns 3.13, rounded to 2 decimals. Understand that this is now a 64bit floating number with an error, the error is just to small for node-red to display it and it's rounded automatically, but it's still there.
If you put in 0.0001 in netvar you get 0. Not very usefull!

How it's implemented in node-red-contrib-nvl is technically correct. It's just that when going from 32bit to 64bit the error can be to high for automatic rounding. You can do two things:

- Use LREAL in the plc as this is already 64bit. There still can be errors, but it won't be displayed.
- Round your values yourself to ex. 6 decimals: `Math.round(value*1000000)/1000000;` I won't build this in because I don't know what values you want to represent.
